server:
  port: 8000  #配置项目启动端口
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql8以上
    url: jdbc:mysql://118.31.116.39:3306/motion #数据库连接地址
    username: motion  #数据库登陆用户名
    password: DcRheHNKadRspFiC  #数据库登陆密码

    druid:
      aop-patterns: com.detection.motion.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin   #在此处配置监控页面登陆用户名
        login-password: admin   #在此处配置监控页面登陆密码
        resetEnable: false
      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  mail:
    default-encoding: UTF-8
    host: smtp.163.com   #使用的邮箱服务器
    username: qingganfenxi21@163.com   #邮箱账号
    password: KPICHTQMBVFQGUDA    #开通smtp服务后的授权码
    port: 465   #ssh走的465端口
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

motion:
  api:
    app-id: 25233516    #百度API的app-id
    api-key: w1etS0VbvoMgG0yBi7YpeYUc   #百度API的api-key
    secret-key: r9eE1d3izBep1TYL13oaRzz424avBTjW    #百度API的secret-key

mqtt:
  broker: tcp://118.31.116.39:1883  #配置mqtt服务器地址
