server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.116.39:3306/motion
    username: motion
    password: DcRheHNKadRspFiC

    druid:
      aop-patterns: com.ahpu.motion.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin   #配置druid监控页面登陆用户名
        login-password: admin   #配置druid监控页面登陆密码
        resetEnable: false
      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 3401506758@qq.com
    password: gsxwqkivmfigciji
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

#      spring.mail.properties.mail.smtp.auth=true
#      spring.mail.properties.mail.smtp.starttls.enable=true
#      spring.mail.properties.mail.smtp.starttls.required=true
#      spring.mail.properties.mail.smtp.ssl.enable=true


motion:
  api:
    app-id: "25098237"
    api-key: "CgU3PcsyB4ZGW6jzNX3P68Ij"
    secret-key: "uq1FGSHwRuYA3yRfuwc8YgkglCi5lKW7"

mqtt:
  broker: tcp://118.31.116.39:1883
